import { randomUUID } from 'node:crypto';
import {
  CommunityListing,
  CommunityListingId,
  ConflictError,
  EventId,
  ExternalUrl,
  NotFoundError,
  RateLimitError,
  UnauthorizedError,
  UserId,
  type CommunityListingRepository,
  type ListingLocation,
} from '@pickupvb/domain';
import {
  ApproveCommunityListingClaimCommand,
  ClaimCommunityListingCommand,
  CreateCommunityListingCommand,
  DeleteCommunityListingCommand,
  HideCommunityListingCommand,
  RejectCommunityListingClaimCommand,
  ReportCommunityListingCommand,
  UnhideCommunityListingCommand,
  UpdateCommunityListingCommand,
} from '../messages/index';

const RATE_LIMIT_WINDOW_MS = 24 * 60 * 60 * 1000;
const RATE_LIMIT_MAX = 5;

function toListingLocation(
  loc:
    | {
        addressLine?: string | null | undefined;
        city: string;
        region?: string | null | undefined;
        postalCode?: string | null | undefined;
        country: string;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
      }
    | null
    | undefined,
): ListingLocation | null {
  if (!loc) return null;
  return {
    addressLine: loc.addressLine ?? null,
    city: loc.city,
    region: loc.region ?? null,
    postalCode: loc.postalCode ?? null,
    country: loc.country,
    latitude: loc.latitude ?? null,
    longitude: loc.longitude ?? null,
  };
}

function assertCanManage(
  submitterUserId: string,
  requesterId: string,
  requesterIsAdmin: boolean,
): void {
  if (submitterUserId !== requesterId && !requesterIsAdmin) {
    throw new UnauthorizedError('Only the submitter or a platform admin can manage this listing.');
  }
}

export class CreateCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({
    submitterUserId,
    dto,
  }: CreateCommunityListingCommand): Promise<{ id: string; slug: string }> {
    // The 5/24h cap is an anti-spam guard for regular submitters. Platform
    // admins bulk-import known listings (e.g. the AI paste-to-listing tool),
    // so the limit doesn't apply to them.
    if (!(await this.isPlatformAdmin(submitterUserId))) {
      const since = new Date(Date.now() - RATE_LIMIT_WINDOW_MS);
      const recent = await this.repo.countByUserSince(submitterUserId, since);
      if (recent >= RATE_LIMIT_MAX) {
        throw new RateLimitError('You can submit at most 5 listings per 24 hours.', {
          limit: RATE_LIMIT_MAX,
          windowMs: RATE_LIMIT_WINDOW_MS,
        });
      }
    }

    const listing = CommunityListing.create({
      id: CommunityListingId(randomUUID()),
      submitterUserId: UserId(submitterUserId),
      title: dto.title,
      description: dto.description ?? '',
      externalUrl: ExternalUrl.create(dto.externalUrl),
      externalHostName: dto.externalHostName ?? null,
      startsAt: dto.startsAt,
      endsAt: dto.endsAt ?? null,
      allDay: dto.allDay ?? false,
      location: toListingLocation(dto.location ?? null),
      timeZone: dto.timeZone ?? null,
      surface: dto.surface ?? null,
      format: dto.format ?? null,
      skillLevel: dto.skillLevel ?? null,
    });

    await this.repo.save(listing);
    // Slug is generated by a trigger on insert. Read it back so callers can
    // redirect to the canonical URL.
    const detail = await this.repo.getDetail(String(listing.id), submitterUserId);
    return { id: String(listing.id), slug: detail?.slug ?? String(listing.id) };
  }
}

export class UpdateCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId, dto }: UpdateCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);

    const admin = await this.isPlatformAdmin(requesterId);
    assertCanManage(String(listing.submitterUserId), requesterId, admin);

    listing.update({
      ...(dto.title !== undefined ? { title: dto.title } : {}),
      ...(dto.description !== undefined ? { description: dto.description } : {}),
      ...(dto.externalUrl !== undefined
        ? { externalUrl: ExternalUrl.create(dto.externalUrl) }
        : {}),
      ...(dto.externalHostName !== undefined
        ? { externalHostName: dto.externalHostName ?? null }
        : {}),
      ...(dto.startsAt !== undefined ? { startsAt: dto.startsAt } : {}),
      ...(dto.endsAt !== undefined ? { endsAt: dto.endsAt ?? null } : {}),
      ...(dto.allDay !== undefined ? { allDay: dto.allDay } : {}),
      ...(dto.location !== undefined ? { location: toListingLocation(dto.location ?? null) } : {}),
      ...(dto.timeZone !== undefined ? { timeZone: dto.timeZone ?? null } : {}),
      ...(dto.surface !== undefined ? { surface: dto.surface ?? null } : {}),
      ...(dto.format !== undefined ? { format: dto.format ?? null } : {}),
      ...(dto.skillLevel !== undefined ? { skillLevel: dto.skillLevel ?? null } : {}),
    });

    await this.repo.save(listing);
  }
}

export class DeleteCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: DeleteCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    assertCanManage(String(listing.submitterUserId), requesterId, admin);
    // A claimed listing is linked to a live PickupVB event (and now redirects to
    // it). `delete()` is a hard DB delete that bypasses the aggregate's
    // `remove()` guard, so block it here for non-admins — mirrors the domain
    // invariant "claimed listings cannot be removed." Platform admins keep an
    // escape hatch for genuine cleanup.
    if (listing.status === 'claimed' && !admin) {
      throw new ConflictError('A claimed listing is linked to an event and cannot be deleted.');
    }
    await this.repo.delete(listingId);
  }
}

export class ReportCommunityListingHandler {
  constructor(private readonly repo: CommunityListingRepository) {}

  async execute({
    listingId,
    reporterUserId,
    reason,
  }: ReportCommunityListingCommand): Promise<{ autoHidden: boolean }> {
    // Confirm listing exists so callers get NotFound instead of a generic FK error.
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const wasActive = listing.status === 'active';
    await this.repo.recordReport(listingId, reporterUserId, reason);
    // recordReport fires a DB trigger that flips status active→hidden once
    // reports cross the threshold. Re-read to detect *this* report's transition,
    // so the caller can notify the submitter exactly once — and never for a
    // report against an already-hidden listing. The threshold lives only in the
    // trigger; we read the result rather than duplicate it here.
    if (!wasActive) return { autoHidden: false };
    const after = await this.repo.findById(listingId);
    return { autoHidden: after?.status === 'hidden' };
  }
}

export class HideCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: HideCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    if (!admin) {
      throw new UnauthorizedError('Only platform admins can hide listings.');
    }
    listing.hide();
    await this.repo.save(listing);
  }
}

export class UnhideCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: UnhideCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    if (!admin) {
      throw new UnauthorizedError('Only platform admins can un-hide listings.');
    }
    listing.unhide();
    await this.repo.save(listing);
  }
}

export class ClaimCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly loadEventClaimFacts: (eventId: string) => Promise<{
      hostId: string;
      coHostIds: string[];
      startsAt: Date;
      city: string | null;
      timeZone: string | null;
    } | null>,
  ) {}

  async execute({ listingId, requesterId, eventId }: ClaimCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);

    const facts = await this.loadEventClaimFacts(eventId);
    if (!facts) throw new NotFoundError('Event', eventId);

    const isHost = facts.hostId === requesterId || facts.coHostIds.includes(requesterId);
    if (!isHost) {
      throw new UnauthorizedError(
        'You can only claim a listing with an event you host on PickupVB.',
      );
    }

    // Match check: prevent a host from pointing an unrelated event at any
    // community listing. We require the event to start on the same calendar
    // day (in the venue's timezone) and have the same city as the listing.
    // Loose enough that time-of-day discrepancies between the external post
    // and the host's PickupVB event don't bite; strict enough that random
    // claims are blocked.
    if (!matchesByDateAndCity(listing, facts)) {
      throw new ConflictError(
        'That event does not match this listing. The PickupVB event must be on the same day and in the same city.',
      );
    }

    listing.proposeClaim(EventId(eventId), UserId(requesterId), new Date());
    await this.repo.save(listing);
  }
}

export class ApproveCommunityListingClaimHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, approverId }: ApproveCommunityListingClaimCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);

    const admin = await this.isPlatformAdmin(approverId);
    // Original submitter OR a platform admin can approve. The claimant
    // themselves cannot self-approve even if they happen to be admin of
    // some unrelated surface — platform admin is an explicit role.
    if (String(listing.submitterUserId) !== approverId && !admin) {
      throw new UnauthorizedError(
        'Only the original submitter or a platform admin can approve this claim.',
      );
    }

    listing.approveClaim(new Date());
    await this.repo.save(listing);
  }
}

export class RejectCommunityListingClaimHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, rejecterId }: RejectCommunityListingClaimCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);

    const admin = await this.isPlatformAdmin(rejecterId);
    if (String(listing.submitterUserId) !== rejecterId && !admin) {
      throw new UnauthorizedError(
        'Only the original submitter or a platform admin can reject this claim.',
      );
    }

    listing.rejectClaim();
    await this.repo.save(listing);
  }
}

/**
 * Auto-approve community-listing claims left un-reviewed past a cutoff
 * (the 7-day backstop in audit CL-4). System action — no approver identity,
 * so there's no auth gate; the cron route is the only caller. Returns the
 * approved listings + their claimants so the caller can notify them.
 */
export class AutoApproveExpiredCommunityClaimsHandler {
  constructor(private readonly repo: CommunityListingRepository) {}

  async execute(
    olderThan: Date,
    now: Date = new Date(),
  ): Promise<Array<{ listingId: string; claimantId: string | null }>> {
    const pending = await this.repo.findClaimPendingOlderThan(olderThan);
    const approved: Array<{ listingId: string; claimantId: string | null }> = [];
    for (const listing of pending) {
      listing.approveClaim(now);
      await this.repo.save(listing);
      approved.push({
        listingId: String(listing.id),
        claimantId: listing.claimedByUserId ? String(listing.claimedByUserId) : null,
      });
    }
    return approved;
  }
}

/**
 * "Same calendar day, same city." The day comparison uses the listing's
 * timezone when available (falls back to the event's timezone, then UTC) so
 * that an event scheduled `7pm Pacific` and a listing posted `10pm Pacific`
 * on the same evening match correctly. City comparison is case-insensitive
 * and ignores surrounding whitespace; null on either side fails closed.
 */
function matchesByDateAndCity(
  listing: CommunityListing,
  facts: { startsAt: Date; city: string | null; timeZone: string | null },
): boolean {
  const listingCity = listing.location?.city?.trim().toLowerCase() ?? null;
  const eventCity = facts.city?.trim().toLowerCase() ?? null;
  if (!listingCity || !eventCity || listingCity !== eventCity) return false;

  const tz = listing.timeZone ?? facts.timeZone ?? 'UTC';
  return sameCalendarDayInZone(listing.startsAt, facts.startsAt, tz);
}

/**
 * Compare two `Date`s for "same calendar day in `timeZone`" using the
 * `en-CA` locale's `YYYY-MM-DD` format. Falls back to UTC comparison if
 * the runtime rejects the timezone (defensive — Node's ICU should accept
 * any IANA name).
 */
function sameCalendarDayInZone(a: Date, b: Date, timeZone: string): boolean {
  try {
    const fmt = new Intl.DateTimeFormat('en-CA', {
      timeZone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    });
    return fmt.format(a) === fmt.format(b);
  } catch {
    return a.toISOString().slice(0, 10) === b.toISOString().slice(0, 10);
  }
}
