import { randomUUID } from 'node:crypto';
import {
  CommunityListing,
  ExternalUrl,
  NotFoundError,
  RateLimitError,
  UnauthorizedError,
  type CommunityListingRepository,
  type ListingLocation,
} from '@pickupvb/domain';
import {
  ClaimCommunityListingCommand,
  CreateCommunityListingCommand,
  DeleteCommunityListingCommand,
  HideCommunityListingCommand,
  ReportCommunityListingCommand,
  UnhideCommunityListingCommand,
  UpdateCommunityListingCommand,
} from '../messages';

const RATE_LIMIT_WINDOW_MS = 24 * 60 * 60 * 1000;
const RATE_LIMIT_MAX = 5;

function toListingLocation(
  loc:
    | {
        addressLine?: string | null | undefined;
        city: string;
        region?: string | null | undefined;
        postalCode?: string | null | undefined;
        country: string;
        latitude: number;
        longitude: number;
      }
    | null
    | undefined,
): ListingLocation | null {
  if (!loc) return null;
  return {
    addressLine: loc.addressLine ?? null,
    city: loc.city,
    region: loc.region ?? null,
    postalCode: loc.postalCode ?? null,
    country: loc.country,
    latitude: loc.latitude,
    longitude: loc.longitude,
  };
}

function assertCanManage(
  submitterUserId: string,
  requesterId: string,
  requesterIsAdmin: boolean,
): void {
  if (submitterUserId !== requesterId && !requesterIsAdmin) {
    throw new UnauthorizedError('Only the submitter or a platform admin can manage this listing.');
  }
}

export class CreateCommunityListingHandler {
  constructor(private readonly repo: CommunityListingRepository) {}

  async execute({
    submitterUserId,
    dto,
  }: CreateCommunityListingCommand): Promise<{ id: string; slug: string }> {
    const since = new Date(Date.now() - RATE_LIMIT_WINDOW_MS);
    const recent = await this.repo.countByUserSince(submitterUserId, since);
    if (recent >= RATE_LIMIT_MAX) {
      throw new RateLimitError('You can submit at most 5 listings per 24 hours.', {
        limit: RATE_LIMIT_MAX,
        windowMs: RATE_LIMIT_WINDOW_MS,
      });
    }

    const listing = CommunityListing.create({
      id: randomUUID() as never,
      submitterUserId: submitterUserId as never,
      title: dto.title,
      description: dto.description ?? '',
      externalUrl: ExternalUrl.create(dto.externalUrl),
      externalHostName: dto.externalHostName ?? null,
      startsAt: dto.startsAt,
      endsAt: dto.endsAt ?? null,
      location: toListingLocation(dto.location ?? null),
      surface: dto.surface ?? null,
      format: dto.format ?? null,
      skillLevel: dto.skillLevel ?? null,
    });

    await this.repo.save(listing);
    // Slug is generated by a trigger on insert. Read it back so callers can
    // redirect to the canonical URL.
    const detail = await this.repo.getDetail(String(listing.id), submitterUserId);
    return { id: String(listing.id), slug: detail?.slug ?? String(listing.id) };
  }
}

export class UpdateCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId, dto }: UpdateCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);

    const admin = await this.isPlatformAdmin(requesterId);
    assertCanManage(String(listing.submitterUserId), requesterId, admin);

    listing.update({
      ...(dto.title !== undefined ? { title: dto.title } : {}),
      ...(dto.description !== undefined ? { description: dto.description } : {}),
      ...(dto.externalUrl !== undefined
        ? { externalUrl: ExternalUrl.create(dto.externalUrl) }
        : {}),
      ...(dto.externalHostName !== undefined
        ? { externalHostName: dto.externalHostName ?? null }
        : {}),
      ...(dto.startsAt !== undefined ? { startsAt: dto.startsAt } : {}),
      ...(dto.endsAt !== undefined ? { endsAt: dto.endsAt ?? null } : {}),
      ...(dto.location !== undefined ? { location: toListingLocation(dto.location ?? null) } : {}),
      ...(dto.surface !== undefined ? { surface: dto.surface ?? null } : {}),
      ...(dto.format !== undefined ? { format: dto.format ?? null } : {}),
      ...(dto.skillLevel !== undefined ? { skillLevel: dto.skillLevel ?? null } : {}),
    });

    await this.repo.save(listing);
  }
}

export class DeleteCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: DeleteCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    assertCanManage(String(listing.submitterUserId), requesterId, admin);
    await this.repo.delete(listingId);
  }
}

export class ReportCommunityListingHandler {
  constructor(private readonly repo: CommunityListingRepository) {}

  async execute({
    listingId,
    reporterUserId,
    reason,
  }: ReportCommunityListingCommand): Promise<void> {
    // Confirm listing exists so callers get NotFound instead of a generic FK error.
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    await this.repo.recordReport(listingId, reporterUserId, reason);
  }
}

export class HideCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: HideCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    if (!admin) {
      throw new UnauthorizedError('Only platform admins can hide listings.');
    }
    listing.hide();
    await this.repo.save(listing);
  }
}

export class UnhideCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isPlatformAdmin: (userId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId }: UnhideCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const admin = await this.isPlatformAdmin(requesterId);
    if (!admin) {
      throw new UnauthorizedError('Only platform admins can un-hide listings.');
    }
    listing.unhide();
    await this.repo.save(listing);
  }
}

export class ClaimCommunityListingHandler {
  constructor(
    private readonly repo: CommunityListingRepository,
    private readonly isHostOfEvent: (userId: string, eventId: string) => Promise<boolean>,
  ) {}

  async execute({ listingId, requesterId, eventId }: ClaimCommunityListingCommand): Promise<void> {
    const listing = await this.repo.findById(listingId);
    if (!listing) throw new NotFoundError('CommunityListing', listingId);
    const isHost = await this.isHostOfEvent(requesterId, eventId);
    if (!isHost) {
      throw new UnauthorizedError(
        'You can only claim a listing with an event you host on PickupVB.',
      );
    }
    listing.markClaimed(eventId as never, requesterId as never, new Date());
    await this.repo.save(listing);
  }
}
