import type { Metadata } from 'next';
import { BreadcrumbJsonLd } from '@/app/_components/breadcrumb-jsonld';
import { JsonLd } from '@/components/json-ld';
import { Scheduler } from './_components/scheduler.js';
import { parseEventBinding } from '../_lib/event-binding';
import { loadEventToolContext } from '../_lib/load-event-tool-context';

/**
 * SEO-facing landing page for the free round-robin schedule generator. The
 * interactive scheduler is a small client island (`_components/scheduler.tsx`)
 * so the page stays a server component and exports real metadata + JSON-LD.
 * Backend-free — teams never leave the browser — matching the no-signup posture
 * of the other tools.
 */
export const metadata: Metadata = {
  title: 'Free round-robin schedule generator (any sport)',
  description:
    'Free, no-signup round-robin schedule maker. Paste your teams and get a full schedule where everyone plays everyone once, spread across your courts. Works for volleyball, pickleball, basketball — any sport. Nothing is saved.',
  alternates: { canonical: '/tools/scheduler' },
  keywords: [
    'round robin generator',
    'round robin schedule maker',
    'tournament schedule generator',
    'pool play schedule',
    'league schedule generator',
    'volleyball schedule generator',
  ],
  openGraph: {
    title: 'Free round-robin schedule generator',
    description:
      'Paste your teams and get a full round-robin schedule across your courts. No account, no install.',
    url: '/tools/scheduler',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free round-robin schedule generator',
    description: 'Everyone plays everyone once, spread across your courts. No signup.',
  },
};

const faqs = [
  {
    q: 'Do I need an account?',
    a: 'No. The schedule generator is a free utility — no signup, no install, no payment.',
  },
  {
    q: 'What is a round robin?',
    a: 'A format where every team plays every other team exactly once. With N teams you get N-1 rounds (one extra when an odd count forces a bye).',
  },
  {
    q: 'Can I use more than one court?',
    a: 'Yes. Set the number of courts and the games in each round are spread evenly across them so multiple matches run at once.',
  },
  {
    q: 'What if I have an odd number of teams?',
    a: 'One team sits out each round (a bye). The schedule rotates so every team gets the same number of byes.',
  },
  {
    q: 'Is my schedule saved anywhere?',
    a: 'No. Everything stays in your browser. Nothing is sent to our servers or saved.',
  },
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebApplication',
      name: 'PickupVB Round-Robin Schedule Generator',
      applicationCategory: 'SportsApplication',
      operatingSystem: 'Any (browser)',
      url: 'https://pickupvb.com/tools/scheduler',
      description:
        'Free, no-signup round-robin schedule maker. Paste your teams and get a full schedule across your courts.',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    {
      '@type': 'FAQPage',
      mainEntity: faqs.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    },
  ],
};

export default async function SchedulerPage(props: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  // Bound to an event division (tournament-tools-workflow audit TT-2/TT-5):
  // pre-fill the division's registered teams. The schedule itself stays a
  // preview — the domain has no "save arbitrary matchups" path, so the official
  // slate is generated by the bracket's pool-play config. Unbound → free tool.
  const binding = parseEventBinding(await props.searchParams);
  const ctx = binding ? await loadEventToolContext(binding) : null;
  const islandProps =
    ctx && ctx.divisionId
      ? {
          initialTeams: ctx.teams.map((t) => t.name),
          eventBinding: {
            eventId: ctx.binding.eventId,
            divisionId: ctx.divisionId,
            ret: ctx.binding.ret,
            eventTitle: ctx.eventTitle,
            ...(ctx.divisionLabel ? { divisionLabel: ctx.divisionLabel } : {}),
          },
        }
      : {};

  return (
    <section className="mx-auto max-w-2xl space-y-6">
      <JsonLd data={jsonLd} />
      <BreadcrumbJsonLd
        trail={[
          { name: 'Host tools', path: '/tools' },
          { name: 'Round-robin scheduler', path: '/tools/scheduler' },
        ]}
      />

      <header className="space-y-1">
        <p className="text-primary text-xs font-semibold tracking-wide uppercase">
          Host tool · Free
        </p>
        <h1 className="text-headline-lg font-bold">Round-robin scheduler</h1>
        <p className="text-muted text-sm">
          Paste your teams and get a full round-robin schedule — everyone plays everyone once,
          spread across your courts. Updates live as you type. Nothing is saved.
        </p>
      </header>

      <Scheduler {...islandProps} />

      <div className="text-muted border-border-base rounded-md border border-dashed p-4 text-xs">
        <p className="text-fg font-medium">How it works</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Paste team names, one per line.</li>
          <li>Set how many courts you have — games are split across them each round.</li>
          <li>The schedule builds instantly: every team plays every other once.</li>
          <li>Copy the result to share it anywhere.</li>
        </ul>
      </div>

      <div className="space-y-4">
        <h2 className="text-fg text-title-lg font-semibold">FAQ</h2>
        <dl className="space-y-3">
          {faqs.map((f) => (
            <div key={f.q} className="border-border-base rounded-md border p-3">
              <dt className="text-fg text-sm font-medium">{f.q}</dt>
              <dd className="text-muted mt-1 text-sm">{f.a}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}
